# Site settings
title: vdaubry.github.io
email: vdaubry@gmail.com
author: Vincent Daubry
description: "A blog about backend development, mobile development, and entrepreneurship"
baseurl: ""
url: "http://vdaubry.github.io"
twitter_username: vdaubry
github_username:  vdaubry
linkedin_username: vincent daubry

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
